//refernece : https://processing.org/examples/simpleparticlesystem.html
class BubblesSystem {
  ArrayList<Bubbles> bubbles;
  PVector origin;

  BubblesSystem(PVector position) {
    
    //copy each position generated by bubbles
    origin = position.copy();

    bubbles = new ArrayList<Bubbles>();
    //initialize Bubbles class
  }

  void addBubbles() {
    //Apply the coordinates generated and add them to the Bubbles ArrayList
    bubbles.add(new Bubbles(origin));
  }

  void run() {
    
    addBubbles(); //run the addBubbles() function
    for (int i = bubbles.size()-1; i >= 0; i--) { //for i = the size of the bubbles array, if i is less than or equal to 0, subtract from i
      Bubbles b = bubbles.get(i); //the coordinates of b receives that of bubbles
      b.run(); //run update() and display() functions from Bubbles
      
      if (b.isDead()) {
        bubbles.remove(i); //if the lifespan requirements are achieved, remove the bubble
      }
    }
  }
}
